version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: sakila-webapp
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=sakila
      
    ports:
    - "8082:3000" # Host:Container

