name: Build, Test, and Trigger Portainer Webhook

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: sakila_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: sakila_test
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: Sakila-webApp/app

      - name: Run unit tests
        run: npm test
        working-directory: Sakila-webApp/app

      - name: Install Cypress
        run: npm install cypress --save-dev
        working-directory: Sakila-webApp/app

      - name: Run Cypress tests
        run: npx cypress run --headless
        working-directory: Sakila-webApp/app

      - name: Trigger Portainer webhook
        if: success()
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
