name: Build, Test, and Trigger Portainer Webhook

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: sakila_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: sakila_test
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: Sakila-webApp/app

      - name: Run unit tests
        run: npm test
        working-directory: Sakila-webApp/app

      - name: Install Cypress
        run: npm install cypress --save-dev
        working-directory: Sakila-webApp/app


      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -uroot -prootpassword -e "SELECT 1" sakila_test; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Load schema into test DB
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpassword sakila_test < Sakila-webApp/app/src/db/sakila_testing.sql

      # - name: Seed test DB
      #   run: node src/config/setup-test-db.js
      #   working-directory: Sakila-webApp/app



      - name: Start server
        run: |
          npm run start:test &
          echo "Waiting for server..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/films >/dev/null; then
              echo "Server ready!"
              break
            fi
            sleep 2
          done
        working-directory: Sakila-webApp/app


      - name: Run Cypress tests
        run: npm run cy:run
        working-directory: Sakila-webApp/app

      - name: Trigger Portainer webhook
        if: success()
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
